[
{"location":"Fantasyland","id":98,"name":"Alice in Wonderland","current":0,"height":0,"fastpass":false},
{"location":"Tomorrowland","id":87,"name":"Astro Orbitor","current":8,"height":0,"fastpass":false},
{"location":"Tomorrowland","id":84,"name":"Autopia","current":14,"height":54,"fastpass":true},
{"location":"Frontierland","id":91,"name":"Big Thunder Mountain Railroad","current":19,"height":40,"fastpass":true},
{"location":"Tomorrowland","id":86,"name":"Buzz Lightyear Astro Blasters","current":11,"height":0,"fastpass":true},
{"location":"Fantasyland","id":103,"name":"Casey Jr. Circus Train","current":8,"height":0,"fastpass":false},
{"location":"Critter Country","id":105,"name":"Davy Crockett's Explorer Canoes","current":11,"height":0,"fastpass":false},
{"location":"Fantasyland","id":99,"name":"Dumbo the Flying Elephant","current":11,"height":0,"fastpass":false},
{"location":"Tomorrowland","id":83,"name":"Finding Nemo Submarine Voyage","current":19,"height":0,"fastpass":false},
{"location":"Mickey's Toontown","id":89,"name":"Gadget's Go Coaster","current":14,"height":35,"fastpass":false},
{"location":"New Orleans Square","id":108,"name":"Haunted Mansion","current":14,"height":0,"fastpass":true},
{"location":"Tomorrowland","id":88,"name":"Honey, I Shrunk the Audience","current":8,"height":0,"fastpass":false},
{"location":"Adventureland","id":92,"name":"Indiana Jones Adventure","current":28,"height":46,"fastpass":true},
{"location":"Fantasyland","id":100,"name":"it's a small world","current":14,"height":0,"fastpass":false},
{"location":"Adventureland","id":93,"name":"Jungle Cruise","current":14,"height":0,"fastpass":false},
{"location":"Fantasyland","id":94,"name":"Mad Tea Party","current":11,"height":0,"fastpass":false},
{"location":"Fantasyland","id":95,"name":"Matterhorn Bobsleds","current":14,"height":35,"fastpass":false},
{"location":"Fantasyland","id":96,"name":"Mr. Toad's Wild Ride","current":11,"height":0,"fastpass":false},
{"location":"Fantasyland","id":101,"name":"Peter Pan's Flight","current":11,"height":0,"fastpass":false},
{"location":"Fantasyland","id":104,"name":"Pinocchio's Daring Journey","current":8,"height":0,"fastpass":false},
{"location":"New Orleans Square","id":109,"name":"Pirates of the Caribbean","current":14,"height":0,"fastpass":false},
{"location":"Mickey's Toontown","id":90,"name":"Roger Rabbit's Car Toon Spin","current":11,"height":0,"fastpass":true},
{"location":"Fantasyland","id":97,"name":"Snow White's Scary Adventures","current":11,"height":0,"fastpass":false},
{"location":"Tomorrowland","id":82,"name":"Space Mountain","current":19,"height":40,"fastpass":true},
{"location":"Critter Country","id":106,"name":"Splash Mountain","current":19,"height":40,"fastpass":true},
{"location":"Tomorrowland","id":85,"name":"Star Tours","current":14,"height":40,"fastpass":false},
{"location":"Fantasyland","id":102,"name":"Storybook Land Canal Boats","current":8,"height":0,"fastpass":false},
{"location":"Critter Country","id":107,"name":"The Many Adventures of Winnie the Pooh","current":14,"height":0,"fastpass":false}
]